GET http://localhost:4000/blocks


###
POST http://localhost:4000/blocks
content-type: application/json

###
POST http://localhost:4000/peers
content-type: application/json

{
    "peer": "ws://localhost:4500"
}

###
GET http://localhost:4000/me/balance

###
GET http://localhost:4000/me/address

###
POST http://localhost:4000/transactions/
content-type: application/json

{
    "address": "04666d1ecd0240db02a311e6e88ac320f996ffcae6884637fdac2780b13ab83836f7bb95bb2306af6680d0e8f18fd6004e19583265588a8a8d9f5f3b2fea149903",
    "amount": 10
}

###
GET http://localhost:4000/transactions/

###
GET http://localhost:4500/transactions/